FROM python:3.6-slim

RUN echo 'Dockerfile-Celery'
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt

ENV APP_SETTINGS="config.ProductionConfig"

ENTRYPOINT celery -A application.tasks:celery worker --concurrency=10 --loglevel=info