FROM python:3.6-slim

RUN echo 'Dockerfile-Application'

RUN mkdir /app
WORKDIR /app
COPY . /app

RUN pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt

# expose port
EXPOSE 5000

# run
ENTRYPOINT flask db upgrade && flask run --host=0.0.0.0
