"""empty message

Revision ID: 342a100a1cb8
Revises: f1c5b3f12577
Create Date: 2018-10-11 14:35:59.058658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342a100a1cb8'
down_revision = 'f1c5b3f12577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_on')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
